name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate antlr4 dependencies
      run: antlr4 -Dlanguage=Python3 -Xexact-output-dir -visitor project/lang.g4 -o project/lang

    - name: Run tests
      run: |
        python scripts/run_tests.py
